apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dex.fullname" . }}
  labels:
    app: {{ template "dex.name" . }}
    chart: {{ template "dex.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yaml: |-
    issuer: {{ .Values.config.issuer }}
    storage:
      {{- if or .Values.postgresql.enabled .Values.cloudsql.enabled }}
      type: postgres
      {{- else }}
      type: {{ .Values.config.storage.type }}
      {{- end }}
      config:
        {{- if .Values.postgresql.enabled }}
        host: {{ printf "%s-postgresql.%s.svc.cluster.local:5432" .Release.Name .Release.Namespace }}
        database: {{ .Values.postgresql.postgresqlDatabase }}
        user: {{ .Values.postgresql.postgresqlUsername }}
        password: {{ .Values.postgresql.postgresqlPassword }}
        {{- else if .Values.cloudsql.enabled }}
        host: {{ default "localhost:5432" .Values.config.storage.config.host }}
        database: {{ .Values.config.storage.config.database }}
        user: {{ .Values.config.storage.config.user }}
        password: {{ .Values.config.storage.config.password }}
        {{- else }}
{{ toYaml .Values.config.storage.config | indent 8 }}
        {{- end }}
        ssl:
          mode: {{ default "disable" .Values.config.storage.config.ssl.mode }}
    logger:
      level: {{ default "debug" .Values.config.logger.level }}
    web:
      http: {{ .Values.config.web.bind }}:{{ .Values.config.web.port }}
      {{- if .Values.config.web.tls.enabled }}
      tlsCert: /etc/dex/tls/https/server/tls.crt
      tlsKey: /etc/dex/tls/https/server/tls.key
      {{ end }}
    telemetry:
      http: {{ .Values.config.telemetry.bind }}:{{ .Values.config.telemetry.port }}
    grpc:
      addr: {{ .Values.config.grpc.bind }}:{{ .Values.config.grpc.port }}
      {{- if .Values.config.grpc.tls.enabled }}
      tlsCert: /etc/dex/tls/grpc/server/tls.crt
      tlsKey: /etc/dex/tls/grpc/server/tls.key
      {{- if .Values.config.grpc.tls.clientAuthEnabled }}
      tlsClientCA: /etc/dex/tls/grpc/ca/ca.crt
      {{- end }}
      {{ end }}
    frontend:
      theme: {{ default "coreos" .Values.config.frontend.theme }}

{{- with .Values.config.staticClients }}
    staticClients:
{{ toYaml . | indent 6 }}
{{- end }}
    connectors:
{{- range $key, $value := .Values.config.connectors }}
    - id: {{ $value.id }}
      type: {{ $value.type }}
      name: {{ $value.name }}
      config:
        {{ toYaml $value.config | nindent 8 }}
{{- end }}
    enablePasswordDB: {{ .Values.config.enablePasswordDB }}
{{- with .Values.config.staticPasswords }}
    staticPasswords:
{{ toYaml . | indent 6 }}
{{- end }}
