{{- if and .Values.tls.enabled (not .Values.tls.existingSecret ) }}
{{- $externalHost := join " " .Values.tls.SANList }}
{{- $ca := genCA "dex-ca" 1000 }}
{{- $cn := printf "%s-%s.%s.svc" .Release.Name .Chart.Name .Release.Namespace }}
{{- $server := genSignedCert $cn (list "127.0.0.1") (list $cn $externalHost ) 365 $ca -}}
{{- $client := genSignedCert "" nil nil 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-server" ( include "dex.fullname" . ) | quote }}
  labels:
    app: {{ template "dex.name" . }}
    chart: {{ template "dex.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $server.Cert }}
  tls.key: {{ b64enc $server.Key }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-client" ( include "dex.fullname" . ) | quote }}
  labels:
    app: {{ template "dex.name" . }}
    chart: {{ template "dex.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $client.Cert }}
  tls.key: {{ b64enc $client.Key }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-ca" ( include "dex.fullname" . ) | quote }}
  labels:
    app: {{ template "dex.name" . }}
    chart: {{ template "dex.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $ca.Cert }}
  tls.key: {{ b64enc $ca.Key }}

{{- end }}
