apiVersion: v1
kind: Service
metadata:
  name: {{ template "dex.fullname" . }}
  labels:
    app: {{ template "dex.name" . }}
    chart: {{ template "dex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type}}
  sessionAffinity: None
  ports:
  - name: http-grpc
    port: {{ .Values.config.grpc.port }}
    targetPort: grpc
  - name: http
    port: {{ .Values.config.web.port }}
    targetPort: http
{{- if hasKey .Values.service "externalIPs" }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "dex.name" . }}
    release: {{ .Release.Name | quote }}
