# Default values for dex
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

image: banzaicloud/dex-shim
imageTag: "0.3.4"
imagePullPolicy: "IfNotPresent"

replicas: 1

postgresql:
  enabled: true
  postgresqlUsername: dex
  postgresqlPassword: foo
  postgresqlDatabase: dex_db

cloudsql:
  enabled: false
  image:
    repository: gcr.io/cloudsql-docker/gce-proxy
    tag: 1.11
    pullPolicy: IfNotPresent
  instance: ""

exampleApp:
  enabled: false
  clientID: ""
  clientSecret: ""
  redirectURI: ""

# resources:
  # limits:
    # cpu: 100m
    # memory: 50Mi
  # requests:
    # cpu: 100m
    # memory: 50Mi

ports:
  - name: http
    containerPort: 5556
    protocol: TCP
  - name: grpc
    containerPort: 5557
    protocol: TCP
  - name: telemetry
    containerPort: 5558
    protocol: TCP

service:
  type: ClusterIP
  annotations: {}

extraVolumes: []
extraVolumeMounts: []

tls:
  enabled: true
  existingSecret: ""
  IPList: []
  SANList: []

env: []
envFrom: []

rbac:
  enabled: true

serviceAccount:
  create: true
  name:

config:
  issuer: "http://127.0.0.1:5556/dex"

  logger:
    level: ""

  web:
    bind: 0.0.0.0
    port: 5556
    tls:
      enabled: false

  grpc:
    bind: 0.0.0.0
    port: 5557
    tls:
      enabled: true
      clientAuth: false

  telemetry:
    bind: 0.0.0.0
    port: 5558

  frontend:
    theme: ""

  storage:
    type: ""
    config:
      database: ""
      user: ""
      password: ""
      host: ""
      ssl:
        mode: ""

  staticClients: []

  connectors: {}

  enablePasswordDB: false
  staticPasswords: []

nodeSelector: {}

ingress:
  enabled: false
  annotations: {}
#    kubernetes.io/ingress.class: traefik
#    ingress.kubernetes.io/ssl-redirect: "false"
#    traefik.frontend.rule.type: PathPrefix
  hosts:
    - "/"
#    - "domain.com/xyz"
#    - "domain.com"
  tls: []
#    - secretName: chart-example-tls
#      hosts:
#        - chart-example.local